[package]
name = "bsm_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.15.0"
rand = "0.8.5"
ndarray = "0.15.4"